server:
  port: 9000
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/token-data
    username: postgres
    password: naik44
    driver-class-name: org.postgresql.Driver

jwt:
  secret: JwtToken
